name: flutter_advanced_table
description: "Effortlessly build beautiful, interactive, and feature-rich data tables in Flutter."
version: 1.0.0
homepage:

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

